=== morooLee/github-pages/public/blog-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Blog",
  "description": "Blog Data",
  "type": "object",
  "properties": {
    "posts": {
      "type": "array",
      "items": [{ "$ref": "#/definitions/Post" }]
    },
    "categories": {
      "type": "array",
      "items": [{ "$ref": "#/definitions/Category" }]
    },
    "tags": {
      "type": "array",
      "items": [{ "$ref": "#/definitions/Tag" }]
    },
    "series": {
      "type": "array",
      "items": [{ "$ref": "#/definitions/Series" }]
    }
  },
  "required": ["posts", "categories", "tags", "series"],
  "definitions": {
    "Post": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "minimum": 1,
          "exclusiveMinimum": false
        },
        "slug": { "type": "string" },
        "title": { "type": "string" },
        "description": { "type": "string" },
        "coverImageUrl": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "coverBackgroundColor": { "type": "string" },
        "createdAt": { "type": "string", "format": "date-time" },
        "updatedAt": { "type": "string", "format": "date-time" },
        "category": {
          "type": "object",
          "properties": { "main": "string", "sub": "string" },
          "required": ["main", "sub"]
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "series": {
          "anyOf": [
            {
              "type": "object",
              "properties": { "name": "string", "number": "integer" },
              "required": ["name", "number"]
            },
            {
              "type": "null"
            }
          ]
        },
        "content": { "type": "string" }
      },
      "required": [
        "id",
        "slug",
        "title",
        "description",
        "coverImageUrl",
        "coverBackgroundColor",
        "createdAt",
        "updatedAt",
        "category",
        "tags",
        "series",
        "content"
      ]
    },
    "Category": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "parent": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "children": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "postIds": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      },
      "required": ["name", "parent", "children", "postIds"]
    },
    "Tag": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "postIds": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      },
      "required": ["name", "postIds"]
    },
    "Series": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "postIds": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      },
      "required": ["name", "postIds"]
    }
  }
}

=== morooLee/github-pages/public/blog.json
{
  "posts": [
    {
      "id": 7,
      "slug": "깃허브-기반의-마크다운-이모지-모음",
      "title": "깃허브 기반의 마크다운 이모지 모음",
      "description": "깃허브 플랫폼에서 마크다운 문서에 사용 가능한 이모지들의 Short Code 모음집",
      "coverBackgroundColor": "hsl(348, 100%, 80%)",
      "createdAt": "2022. 3. 21.",
      "updatedAt": "2022. 3. 21.",
      "category": {
        "main": "Markup",
        "sub": "Markdown"
      },
      "tags": [
        "github",
        "markdown",
        "emoji",
        "cheat-sheet",
        "short-code",
        "깃허브",
        "마크다운",
        "이모지"
      ],
      "published": true,
      "content": "\n## 이모지\n\n### 이모지란?\n\n이모지는 일본어 絵文字(えもじ, 絵/繪(그림) + 文字(문자))의 합성어로 그림 형태의 유니코드 문자입니다.  \n이모지에 대한 자세한 내용은 [이모지 및 이모티콘에 대한 이야기](/posts/이모지-및-이모티콘에-대한-이야기)에서 다루었으니 궁금 하시거나 관심 있으신 분은 한번 읽어보는 것을 추천드립니다.\n\n### 마크다운에서 이모지 사용하기\n\n마크다운에서 이모지를 사용하는 방법은 콜론(:)과 콜론(:) 사이에 Short Code를 입력하면 됩니다.  \n예를 들어 :grinning: 이모지를 사용하고 싶으면 `:grinning:`을 입력하면 됩니다.\n\n## 깃허브 기반의 이모지 모음\n\n마크다운에서 사용하는 이모지의 Short Codes는 이모지를 구현하는 플랫폼마다 다릅니다.  \n예를 들어 여자 경찰의 :policeman: 이모지인 경우 [Github](https://github.com)에서는 Short Code가 `:policeman:`인데 반면, [Slack](https://slack.com/intl/ko-kr)에서는 `:female-police-officer:`이고, [Emojipedia](https://emojipedia.org)에서는 `:woman_police_officer:`로 사용합니다.  \nShort Codes 관련해서 보다 자세한 내용은 [Emoji Shortcodes](https://emojipedia.org/shortcodes)에서 확인 가능합니다.\n\n본론으로 돌아와 아래 이모지 모음집은 Github에서 사용하는 Short Codes를 기반으로 만든 모음집입니다.  \n따라서, 다른 플랫폼에서는 이모지가 보이지 않을 수 있는 점 참고 바랍니다.\n\n### Smileys & Emotion\n\n#### Face Smiling\n\n|          Icon           | Short Code                        |        Icon        | Short Code           |\n| :---------------------: | --------------------------------- | :----------------: | -------------------- |\n|       :grinning:        | `:grinning:`                      |      :smiley:      | `:smiley:`           |\n|         :smile:         | `:smile:`                         |       :grin:       | `:grin:`             |\n|       :laughing:        | `:laughing:` <br /> `:satisfied:` |   :sweat_smile:    | `:sweat_smile:`      |\n|         :rofl:          | `:rofl:`                          |       :joy:        | `:joy:`              |\n| :slightly_smiling_face: | `:slightly_smiling_face:`         | :upside_down_face: | `:upside_down_face:` |\n|         :wink:          | `:wink:`                          |      :blush:       | `:blush:`            |\n|       :innocent:        | `:innocent:`                      |                    |                      |\n\n#### Face Affection\n\n|               Icon               | Short Code                         |          Icon          | Short Code               |\n| :------------------------------: | ---------------------------------- | :--------------------: | ------------------------ |\n| :smiling_face_with_three_hearts: | `:smiling_face_with_three_hearts:` |      :heart_eyes:      | `:heart_eyes:`           |\n|          :star_struck:           | `:star_struck:`                    |    :kissing_heart:     | `:kissing_heart:`        |\n|            :kissing:             | `:kissing:`                        |       :relaxed:        | `:relaxed:`              |\n|      :kissing_closed_eyes:       | `:kissing_closed_eyes:`            | :kissing_smiling_eyes: | `:kissing_smiling_eyes:` |\n|     :smiling_face_with_tear:     | `:smiling_face_with_tear:`         |                        |                          |\n\n#### Face Tongue\n\n|              Icon              | Short Code                       |        Icon        | Short Code           |\n| :----------------------------: | -------------------------------- | :----------------: | -------------------- |\n|             :yum:              | `:yum:`                          | :stuck_out_tongue: | `:stuck_out_tongue:` |\n| :stuck_out_tongue_winking_eye: | `:stuck_out_tongue_winking_eye:` |    :zany_face:     | `:zany_face:`        |\n| :stuck_out_tongue_closed_eyes: | `:stuck_out_tongue_closed_eyes:` | :money_mouth_face: | `:money_mouth_face:` |\n\n#### Face Hand\n\n|      Icon       | Short Code        |       Icon        | Short Code          |\n| :-------------: | ----------------- | :---------------: | ------------------- |\n|     :hugs:      | `:hugs:`          | :hand_over_mouth: | `:hand_over_mouth:` |\n| :shushing_face: | `:shushing_face:` |    :thinking:     | `:thinking:`        |\n\n#### Face Neutral Skeptical\n\n|        Icon         | Short Code            |       Icon       | Short Code         |\n| :-----------------: | --------------------- | :--------------: | ------------------ |\n| :zipper_mouth_face: | `:zipper_mouth_face:` | :raised_eyebrow: | `:raised_eyebrow:` |\n|   :neutral_face:    | `:neutral_face:`      | :expressionless: | `:expressionless:` |\n|     :no_mouth:      | `:no_mouth:`          | :face_in_clouds: | `:face_in_clouds:` |\n|       :smirk:       | `:smirk:`             |    :unamused:    | `:unamused:`       |\n|     :roll_eyes:     | `:roll_eyes:`         |   :grimacing:    | `:grimacing:`      |\n|   :face_exhaling:   | `:face_exhaling:`     |   :lying_face:   | `:lying_face:`     |\n\n#### Face Sleepy\n\n|    Icon    | Short Code   |      Icon       | Short Code        |\n| :--------: | ------------ | :-------------: | ----------------- |\n| :relieved: | `:relieved:` |    :pensive:    | `:pensive:`       |\n|  :sleepy:  | `:sleepy:`   | :drooling_face: | `:drooling_face:` |\n| :sleeping: | `:sleeping:` |                 |                   |\n\n#### Face Unwell\n\n|           Icon           | Short Code                 |          Icon           | Short Code                |\n| :----------------------: | -------------------------- | :---------------------: | ------------------------- |\n|          :mask:          | `:mask:`                   | :face_with_thermometer: | `:face_with_thermometer:` |\n| :face_with_head_bandage: | `:face_with_head_bandage:` |    :nauseated_face:     | `:nauseated_face:`        |\n|     :vomiting_face:      | `:vomiting_face:`          |     :sneezing_face:     | `:sneezing_face:`         |\n|        :hot_face:        | `:hot_face:`               |       :cold_face:       | `:cold_face:`             |\n|       :woozy_face:       | `:woozy_face:`             |      :dizzy_face:       | `:dizzy_face:`            |\n| :face_with_spiral_eyes:  | `:face_with_spiral_eyes:`  |    :exploding_head:     | `:exploding_head:`        |\n\n#### Face Hat\n\n|       Icon        | Short Code          |      Icon       | Short Code        |\n| :---------------: | ------------------- | :-------------: | ----------------- |\n| :cowboy_hat_face: | `:cowboy_hat_face:` | :partying_face: | `:partying_face:` |\n| :disguised_face:  | `:disguised_face:`  |                 |                   |\n\n#### Face Glasses\n\n|      Icon      | Short Code       |    Icon     | Short Code    |\n| :------------: | ---------------- | :---------: | ------------- |\n|  :sunglasses:  | `:sunglasses:`   | :nerd_face: | `:nerd_face:` |\n| :monocle_face: | `:monocle_face:` |             |               |\n\n#### Face Concerned\n\n|           Icon           | Short Code                 |          Icon           | Short Code                |\n| :----------------------: | -------------------------- | :---------------------: | ------------------------- |\n|        :confused:        | `:confused:`               |        :worried:        | `:worried:`               |\n| :slightly_frowning_face: | `:slightly_frowning_face:` |     :frowning_face:     | `:frowning_face:`         |\n|       :open_mouth:       | `:open_mouth:`             |        :hushed:         | `:hushed:`                |\n|       :astonished:       | `:astonished:`             |        :flushed:        | `:flushed:`               |\n|     :pleading_face:      | `:pleading_face:`          |       :frowning:        | `:frowning:`              |\n|       :anguished:        | `:anguished:`              |        :fearful:        | `:fearful:`               |\n|       :cold_sweat:       | `:cold_sweat:`             | :disappointed_relieved: | `:disappointed_relieved:` |\n|          :cry:           | `:cry:`                    |          :sob:          | `:sob:`                   |\n|         :scream:         | `:scream:`                 |      :confounded:       | `:confounded:`            |\n|       :persevere:        | `:persevere:`              |     :disappointed:      | `:disappointed:`          |\n|         :sweat:          | `:sweat:`                  |         :weary:         | `:weary:`                 |\n|       :tired_face:       | `:tired_face:`             |     :yawning_face:      | `:yawning_face:`          |\n\n#### Face Negative\n\n|     Icon      | Short Code      |          Icon          | Short Code               |\n| :-----------: | --------------- | :--------------------: | ------------------------ |\n|   :triumph:   | `:triumph:`     |         :pout:         | `:pout:` <br /> `:rage:` |\n|    :angry:    | `:angry:`       |     :cursing_face:     | `:cursing_face:`         |\n| :smiling_imp: | `:smiling_imp:` |         :imp:          | `:imp:`                  |\n|    :skull:    | `:skull:`       | :skull_and_crossbones: | `:skull_and_crossbones:` |\n\n#### Face Costume\n\n|      Icon       | Short Code                                 |       Icon        | Short Code          |\n| :-------------: | ------------------------------------------ | :---------------: | ------------------- |\n|    :hankey:     | `:hankey:` <br /> `:poop:` <br /> `:shit:` |   :clown_face:    | `:clown_face:`      |\n| :japanese_ogre: | `:japanese_ogre:`                          | :japanese_goblin: | `:japanese_goblin:` |\n|     :ghost:     | `:ghost:`                                  |      :alien:      | `:alien:`           |\n| :space_invader: | `:space_invader:`                          |      :robot:      | `:robot:`           |\n\n#### Cat Face\n\n|     Icon      | Short Code      |       Icon        | Short Code          |\n| :-----------:
